### ISSUE TITLE
Where would you load initial state (if you had saved todo items to load)

### ISSUE THREAD

**Issue by ryancole** [compedit/flummox-todomvc#1]
Hi there! I've really found this repository to be a huge help in learning how to compose an app that uses react and flummox. I'm entirely new to the tools.

I'm trying to figure out where you'd load initial state. I've see it done a few ways, but I'm curious how you'd do it in this app. Lets say you've got some todo items that you've saved in local storage or a database or something. Where would you fetch those and get them into your store's state?

I've seen it suggested to do the actual ajax query in react's `componentDidMount`, and trigger an action, passing in the result of the ajax to that action. That data would flow along into the store's state and back into the view as your initial state.

I've also seen it suggested to do the ajax inside of the action itself, which flummox seems to support pretty well with their async await support. I guess in this scenario you'd just trigger some get initial state action?

**Comment by compedit** [comment]
Hey, glad I could help!

I try to do all the actual fetching inside of utility classes, similar to the [official example](https://github.com/facebook/flux/tree/master/examples/flux-chat).

And I've found [this thread really helpful](https://groups.google.com/d/msg/reactjs/QQ-0dJ4eYUc/L5mHbyMLlRAJ). Essentially, all the ajax work is done in util files, and it doesn't really matter *where* you call for data, so long as it's passed back into the system through a `util -> action -> dispatcher -> store` format.

But specifically in this app, I would probably call for it in AppBootstrap.js before the Router.run method.

Something like, `LocalStorageUtil.initialize()` would load any todos, then call some `ExternalActions.receiveTodos` action, which would be listened to by `TodoStore.loadTodos()` and they would be inserted into state.  I'll try to get an example up here soon, that would actually be pretty cool for this repo!
